#@ load("@ytt:data", "data")
---
primary:
  persistence:
    enabled: true
    storageClass: "tanzu-sp"

auth:
  database: #@ data.values.dbName
  username: #@ data.values.dbUser

global:
  postgresql:
    auth:      
      existingSecret: #@ data.values.secretName
