primary:
  persistence:
    enabled: true
    storageClass: "tanzu-sp"

auth:
  database: music
  username: "postgres"

global:
  postgresql:
    auth:      
      existingSecret: "vac-db-binding-compatible"