#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stk-secret-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.secretName
  namespace:  #@ data.values.workloadNamespace
type: Opaque
stringData:
  type: postgresql
  provider: vac
  host: #@ data.values.dbHost
  port: "5432"
  database: #@ data.values.dbName
  username: #@ data.values.dbUser
  password: #@ data.values.dbPassword
  postgres-password: #@ data.values.dbPassword
---
apiVersion: v1
items:
- apiVersion: services.apps.tanzu.vmware.com/v1alpha1
  kind: ResourceClaim
  metadata:
    name: music-database
    namespace: #@ data.values.workloadNamespace
  spec:
    ref:
      apiVersion: v1
      kind: Secret
      name: #@ data.values.secretName
